import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

clr.AddReference('System')
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

#Preparing input from dynamo to revit
element = UnwrapElement(IN[0])

#Do some action in a Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
collector = FilteredElementCollector(doc)
targetCategory = BuiltInCategory.OST_TitleBlocks
tBlocks = collector.OfClass(FamilyInstance).OfCategory(targetCategory).ToElements()

dict = {}

for t in tBlocks:
    dict[t.Name] = t.GetTypeId()
    
newSheet = ViewSheet.Create(doc, dict['Test 30x42'])


TransactionManager.Instance.TransactionTaskDone()

OUT = dict
